biblia курсач/Models/librarian.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblia_курсач.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class librarian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public librarian()
        {
            this.issuance_of_books = new HashSet<issuance_of_books>();
        }
    
        public int id { get; set; }
        public string FIO { get; set; }
        public byte[] photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issuance_of_books> issuance_of_books { get; set; }
    }
}

biblia курсач/Controllers/librariansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using biblia_курсач.Models;

namespace biblia_курсач.Controllers
{
    public class librariansController : Controller
    {
        private bibliaEntities db = new bibliaEntities();

        // GET: librarians
        public ActionResult Index()
        {
            return View(db.librarian.ToList());
        }

        // GET: librarians/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            librarian librarian = db.librarian.Find(id);
            if (librarian == null)
            {
                return HttpNotFound();
            }
            return View(librarian);
        }

        // GET: librarians/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: librarians/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id, FIO, photo")] librarian people, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        people.photo = reader.ReadBytes(upload.ContentLength);
                    }
                }
                db.librarian.Add(people);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_model = new SelectList(db.librarian, "id", "FIO", people.id);
            return View(people);
        }


        // GET: librarians/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            librarian librarian = db.librarian.Find(id);
            if (librarian == null)
            {
                return HttpNotFound();
            }
            return View(librarian);
        }

        // POST: librarians/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. 
        // Дополнительные сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,FIO,photo")] librarian librarian, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(librarian).State = EntityState.Modified;
                    if (upload != null && upload.ContentLength > 0)
                    {
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            librarian.photo = reader.ReadBytes(upload.ContentLength);
                        }
                        db.SaveChanges();
                    }

                    else
                    {
                        db.Entry(librarian).Property(m => m.photo).IsModified = false;
                        db.SaveChanges();
                    }

                    return RedirectToAction("Index");
                }
            }
            catch (Exception e) { }
            return View(librarian);
        }

      

        // GET: librarians/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            librarian librarian = db.librarian.Find(id);
            if (librarian == null)
            {
                return HttpNotFound();
            }
            return View(librarian);
        }

        // POST: librarians/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            librarian librarian = db.librarian.Find(id);
            db.librarian.Remove(librarian);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

biblia курсач/Views/librarians/Create.cshtml
@model biblia_курсач.Models.librarian

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm(Html.BeginForm("Create", "librarians", null, FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>librarian</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FIO, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.photo, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" value="Обзор..." />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Добавить" class="btn btn-default" />
        </div>
    </div>

    @*<div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>*@
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

biblia курсач/Views/librarians/Delete.cshtml
@model biblia_курсач.Models.librarian

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>librarian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

biblia курсач/Views/librarians/Details.cshtml
@model biblia_курсач.Models.librarian

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>librarian</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FIO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.photo)*@
            @{ var item = Model;
                byte[] photo = item.photo;
                string imageSrc = null;
                if (photo != null)
                {
                    MemoryStream ms = new MemoryStream();
                    ms.Write(photo, 0, photo.Length);
                    string imageBase64 = Convert.ToBase64String(ms.ToArray());
                    imageSrc = string.Format("data:image/jpg;base64,{0}", imageBase64);
                    string base64String = Convert.ToBase64String(photo, 0, photo.Length);
                }
            }

            <img src="@imageSrc" alt="Image" width="150" height="100" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

biblia курсач/Views/librarians/Edit.cshtml
@model biblia_курсач.Models.librarian

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm(Html.BeginForm("Edit", "librarians", null, FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>librarian</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.FIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FIO, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.photo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.photo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.photo, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="editor-label">Фото</div>
        <div class="editor-field">
            @if (Model.photo == null)
            {
                @:None
            }
            else
            {
                byte[] photo = Model.photo;
                string imageSrc = null;
                if (photo != null)
                {
                    MemoryStream ms = new MemoryStream();
                    ms.Write(photo, 0, photo.Length);
                    string imageBase64 = Convert.ToBase64String(ms.ToArray());
                    imageSrc = string.Format("data:image/jpg;base64,{0}", imageBase64);
                    string base64String = Convert.ToBase64String(photo, 0, photo.Length);
                }

                <img width="250" height="150" src="@imageSrc" />
            }
            <div>Выбрать новую фотографию: <input type="file" name="upload" /></div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

biblia курсач/Views/librarians/Index.cshtml
@model IEnumerable<biblia_курсач.Models.librarian>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FIO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FIO)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.photo)*@

            @{ byte[] photo = item.photo;
                string imageSrc = null;
                if (photo != null)
                {
                    MemoryStream ms = new MemoryStream();
                    ms.Write(photo, 0, photo.Length);
                    string imageBase64 = Convert.ToBase64String(ms.ToArray());
                    imageSrc = string.Format("data:image/jpg;base64,{0}", imageBase64);
                    string base64String = Convert.ToBase64String(photo, 0, photo.Length);
                }
            }

            <img src="@imageSrc" alt="Image" width="150" height="100" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>